### ISSUE TITLE
Convert "ONLINE!" from header image to path.

### ISSUE THREAD

**Issue by tyrasd** [openstreetmap/stateofthemap-2020#31]
If a user doesn't have the _Roboto_ font installed, the result doesn't look exactly the same on every system. E.g. this is how it looks like for me on Ubuntu (Firefox):

![image](https://user-images.githubusercontent.com/1927298/78709780-87a0f180-7914-11ea-8c1b-a86264060ccc.png)

on Windows it's not that bad, but it's also not 100% as it should be. On Android it is fine.

This could be solved by converting the text to a path. @YaguraStation – can you take care of that, perhaps?

**Comment by YaguraStation** [comment]
No problem. See PR #32 

Follow-up editors will have to write it out again, which shouldn't be a problem.
