### ISSUE TITLE
new header section

### ISSUE THREAD

**Issue by YaguraStation** [openstreetmap/stateofthemap-2020#4]
https://github.com/openstreetmap/stateofthemap-2020/pull/3 contains my suggestion with a background image and logo. I tested two versions (see below) and liked the simple, square one more. Reject PR with comments if you don't like it, or discuss here. 

![proposal-logo-square](https://user-images.githubusercontent.com/23151113/67957274-06735f00-fbfe-11e9-8706-1941b2f5599b.png)

![proposal-logo-rectangle](https://user-images.githubusercontent.com/23151113/67957273-05dac880-fbfe-11e9-874e-663cd5cc730b.png)

**Comment by tyrasd** [comment]
the square one looks great. thanks!
