### ISSUE TITLE
Can't tell when anything will end

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/stateofthemap-2020#49]
Looking at https://2020.stateofthemap.org/programme/ the user cannot tell when anything will end.
E.g., he wants to know when he can go to bed each day. At the end of day one he sees
`22:15	Meet an OpenStreetMapper`
but even clicking on it does not reveal how long it will run.
Maybe "there are no set limits for the ends of anything" in fact.

**Comment by tyrasd** [comment]
the page now mentions talk lengths: https://github.com/openstreetmap/stateofthemap-2020/commit/cea0a2c3174160d8f293a40e3810211b4c8bc1c9

**Comment by Zverik** [comment]
23:00 UTC Saturday, 22:00 UTC Sunday.
