### ISSUE TITLE
Add test live stream to homepage

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/stateofthemap-2020#53]
Are you sure the live streaming will work  right out of the box? Shouldn't there be a test live stream that people can connect to from the homepage before the conference starts so that they can work out any bugs on their end?

**Comment by tyrasd** [comment]
The live stream will be on the same platform as last year's live streaming of SotM 2019: https://streaming.media.ccc.de

This platform streams many event, some even (much) larger than a typical state of the map. I don't expect any issues in that regard.

Or do you mean so that people can test their own set-up?

**Comment by jidanni** [comment]
Yes, I mean so we home users can test.
Maybe in the FAQ have a link to https://streaming.media.ccc.de/ ... but that site has nothing currently running that we can attach to to test. (No 24-hours test screen.)

E.g., today I was supposed to watch a live stream on Facebook. But found due to my bandwidth, I needed to wait until the stream was over and it became a .mp4 or whatever, before I could watch it.

**Comment by jidanni** [comment]
On https://streaming.media.ccc.de/about/#en it says
> The web player will hopefully choose the right format depending on your operation system and browser. As video streaming in web browsers is still broken in 2020, we recommend to use the streaming client application of choice to consume the streams. We suggest VLC for desktop usage.

OK, we need time to set all this up and test it here at home. Probably about six hours. Imagine if we only discovered all this information when we tried to connect to the opening address. We would miss 1/4 of the conference.

**Comment by tyrasd** [comment]
I've added a link to streaming.media.ccc.de on the FAQ in https://github.com/openstreetmap/stateofthemap-2020/commit/90ea421962f6e890ee0f82896c9169407dcd25da.

**Comment by tyrasd** [comment]
streams have started by now at https://streaming.media.ccc.de/sotm2020, showing some pre-conference filler content
