### ISSUE TITLE
streaming.media.ccc.de/sotm2020 should mention what timezone it is talking about

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/stateofthemap-2020#61]
https://streaming.media.ccc.de/sotm2020/ has lots of times noted on it, hh:mm, but not even in https://streaming.media.ccc.de/sotm2020/about is there any mention of what time zone they are in.

Maybe they are in ".de"'s timezone. But at least some mention on that site should be made.

**Comment by saerdnaer** [comment]
its UTC+2, you can create a pull request for http://github.com/voc/streaming-website/ with some kind of jquery script matching all `<span class="time">12:00</span>` and translate them to the user's local time zone or so

**Comment by jidanni** [comment]
For now it should just note "Times in UTC+2"...

**Comment by jidanni** [comment]
Or, the admin should make it UTC, and note it, so that the times we hear
at least match what we see.
