### ISSUE TITLE
Make conference into daytime for everybody, via 24 hour pad expectation

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/stateofthemap-2020#65]
OK, these worldwide conferences are great, but 2/3 of the world won't be in the "right" timezone. Therefore, for both attendees and presenters, state that all questions and answers should be put on each pad, and then answered within 24 hours.
Thus giving participants time to go to bed, etc.

Indeed another kind of "lightning talk" problem is real lightning: in some warm areas, afternoon lightning storms require all users disconnect all equipment from any wires. So one should expect them to be offline during that time too.

**Comment by YaguraStation** [comment]
Yeah, this doesn't quite fall into the purview of the website and is rather and organisational issue. There's a pad for feedback over here: https://pad.sotm.bitcast.co.za/p/general-feedback

**Comment by jidanni** [comment]
> and then answered within 24 hours.

(Actually it may take users weeks to finally watch the TrackA sessions that they missed because they were watching TrackB, So my idea isn't practical.)
