### ISSUE TITLE
Track 1, Track 2, self-organized sessions, etc. all belong on the same programme page

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/stateofthemap-2020#66]
https://2020.stateofthemap.org/programme/ , in a third column, should show
https://wiki.openstreetmap.org/wiki/State_of_the_Map_2020/self-organized_sessions items,
and a fourth column anything else that is happening in parallel, else most folks won't be aware.

Also nobody knows who the hosts are (the people introducing each talk) are. So put them in column 0, or above each block of talks they are responsible for introducing.

**Comment by YaguraStation** [comment]
Yeah, good input. Would you mind putting it in the feedback pad? https://pad.sotm.bitcast.co.za/p/general-feedback

Since the conf is over and the self-organised session being ephemeral in nature, I think we should close this issue.
