### ISSUE TITLE
osmvideo.cloud68.co spooky login

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/stateofthemap-2020#67]
On https://wiki.openstreetmap.org/wiki/State_of_the_Map_2020/self-organized_sessions there are links to
https://osmvideo.cloud68.co/ which says "Sign in" on it, so we click on
https://osmvideo.cloud68.co/user/signin
and are supposed to enter our email and password, based on the OSM logo we see...

But wouldn't this be a great way to steal people's OSM logins?

Why not have a standard "Login via OSM" which opens a pop-up window to the real OSM site, etc.

We aren't even sure if we "already have an account on osmvideo.cloud68.co".

**Comment by tyrasd** [comment]
The servers are owned and managed by the OSM Foundation. See https://wiki.osmfoundation.org/wiki/Tools/bigbluebutton. Anyway, this is not the right repository to suggest the OSMF bigbluebutton server to use regular OSM user credentials for login (I could assume they wouldn't even want that), since this is about the sotm2020 website repository.

**Comment by jidanni** [comment]
Not sure where to file this in https://github.com/osmfoundation .
Giving up.

**Comment by tyrasd** [comment]
> Not sure where to file this in https://github.com/osmfoundation .
> Giving up.

I would try contacting the "operations working group", see https://wiki.osmfoundation.org/wiki/Operations_Working_Group#Get_in_touch

**Comment by jidanni** [comment]
OK, I emailed them. Thanks.

**Comment by tomhughes** [comment]
I don't think there is any issue tracker that covers it - as far as I know the board organised the video conferencing system so I guess that is who you should contact.

**Comment by jidanni** [comment]
That's good Tom. Alas I don't get your notifications because you are blocking me. I did get
> From: Grant Slater <grant@osm...>
> 
> We don't manage it.
> 
> Bye.

Well maybe somebody will see this thread before next year.
