### ISSUE TITLE
Top right links not easy to see

### ISSUE THREAD

**Issue by indiebio** [openstreetmap/stateofthemap-2020#7]
Depending on the browser window size, the text on the top right corner (Call for participation etc) is hard to see - dark green on the mountain side's forest. Can we have a more opaque transparency perhaps, and a thicker text font could help readability.

**Comment by YaguraStation** [comment]
ACK, depends on resolution and resulting placement of UCT greeting photo. Will experiment with different options. @tyrasd original intent was to meet the mutually agreed colour scheme.
